### ISSUE TITLE
Easier way to run both Error Prone and the Checker Framework

### ISSUE THREAD

**Issue by wmdietl** [kelloggm/checkerframework-gradle-plugin#39]
Checker Framework 2.11.0 uses the javac 9 APIs and on a Java 8 JVM it uses the Error Prone javac to run.

Can we simplify the setup for using both the Checker Framework and Error Prone, described at
https://github.com/kelloggm/checkerframework-gradle-plugin/#incompatibility-with-error-prone ?

I started a PR for a simple demo combination at: https://github.com/typetools/checker-framework/pull/2748
It currently only runs Error Prone and not the Checker Framework.

**Comment by msridhar** [comment]
It would be great if Error Prone and Checker Framework checks could be run simultaneously in a single build.  If there is still a compatibility issue with the dataflow analysis library, maybe Checker Framework could shadow its copy in the release jar?  We could get Error Prone to update their version now but I'm sure this issue will come up again in the future.

**Comment by mernst** [comment]
I have asked them to shadow the Checker Framework classes that they ship. They have promised to do so, but they have not made a release for 6 months.

I didn't make an issue on their issue tracker, so you could make the same request there.

**Comment by vladimirfx** [comment]
Agree - it would be great to run both cherers in one **build**.
But is not a good idea to run Error Prone and Checker Framework in one **task** because Error Prone is much much faster than Checker Framework. In practice this tools has different application - Error Prone must run always in place of regular javac but Checker Framework should be run eventually (for ex. before push or even on CI only).

Consider approach in #43. Error Prone run always in place of regular javac. Checker Framawork run on demand (depends on check task like other code quality tools).

**Comment by msridhar** [comment]
I think it would be nice to support running both tools at the same time, even if in many scenarios it doesn't make sense.  But I think supporting a separate task makes a lot of sense too, if it's feasible.

**Comment by mernst** [comment]
Fixed by 39e3e539ddff4feede116cb23b7d571fe03daee1.
